print ("  OOOOO    SSSSS    V            V    IIIIIII")
print (" O     O   S         V          V        I")
print (" O     O   S          V        V         I")
print (" O     O   SSSSS       V      V          I")
print (" O     O       S        V    V           I")
print (" O     O       S         V  V            I")
print ("  OOOOO    SSSSS          V           IIIIIII")