print(f"  _________________")
print(f" /                \\")
print(f"|      Leones      |")
print(f"|                  /")
print(f"|-----------\-----/")
print(f"|            \\")
print(f"|             \\")
print(f"|              \\")
print(f"|               \\")
print(f"|                \\")
print(f" ")
print(f"          ^        ")
print(f"        /   \\")
print(f"       /     \\")
print(f"      /       \\")
print(f"     /   son   \\")
print(f"    /           \\")
print(f"   /-------------\\")
print(f"  /               \\")
print(f" /                 \\")
print(f"/                   \\")
print(f" ")
print(f"+-------------------")
print(f"|")
print(f"|        cool")
print(f"|")
print(f"+---------------")
print(f"|")
print(f"|")
print(f"|")
print(f"|")
print(f"|")
print(f" ")
print(f"          ^        ")
print(f"        /   \\")
print(f"       /     \\")
print(f"      /       \\")
print(f"     /    y    \\")
print(f"    /           \\")
print(f"   /-------------\\")
print(f"  /               \\")
print(f" /                 \\")
print(f"/                   \\")
print(f" ")
print(f"+------------------")
print(f"|")
print(f"|       super")
print(f"|")
print(f"|")
print(f"+----------------")
print(f"|")
print(f"|")
print(f"|")
print(f"|")
print(f"+-----------------")
print(f" ")
print(f"|")
print(f"|")
print(f"|       ")
print(f"|")
print(f"|")
print(f"|")
print(f"|")
print(f"|")
print(f"|       feroz")
print(f"|")
print(f"|")
print(f"+----------------")
print(f"")
print(f"")
print(f"")
print(f"  \\         /")
print(f" ^           ^ ")
print(f"( )         ( ) ")
print(f" ~           ~")
print(f"")
print(f"\\_____________/") 