print("c   c")
print(" c c ")
print("  c  ")
print("  c  ")
print("  c  ")
print(" c c ")
print("c   c")
print()
print("u     u")
print("u     u")
print("u     u")
print("u     u")
print("u     u")
print("u     u")
print("uuuuuuu")
print()
print("^^^^^^")
print("  ^^ ")
print("  ^^  ")
print("  ^^  ")
print("  ^^  ")
print("  ^^  ")
print("^^^^^^")
print()
print("-------- ")
print("   !!   ")
print("   !!")
print("   !!")
print("   !!")
print("   !!")
print("   !!")
print()
print(" oooooo ")
print("o      o")
print("o      o")
print("o      o")
print("o      o")
print("o      o")
print(" oooooo ")