print("  DDDDDDDDDDDDDDDDD")
print("DDD               DDD")
print("DDD                DDD")
print("DDD                 DDD")
print("DDD                  DDD")
print("DDD                   DDD")
print("DDD                   DDD")
print("DDD                  DDD")
print("DDD                 DDD")
print("DDD                DDD")
print("DDD               DDD")
print(" DDDDDDDDDDDDDDDDDD")
print("  DDDDDDDDDDDDDDDD")

print("IIIIIIIIIIIIIIIIIIIII")
print("IIIIIIIIIIIIIIIIIIIII")
print("         IIII")
print("         IIII")
print("         IIII")
print("         IIII")
print("         IIII")
print("         IIII")
print("         IIII")
print("         IIII")
print("         IIII")
print("IIIIIIIIIIIIIIIIIIIIII")
print("IIIIIIIIIIIIIIIIIIIIII")

print("EEEEEEEEEEEEEEEEEEEEEE")
print("EEEEEEEEEEEEEEEEEEEEEE")
print("EEE")
print("EEE")
print("EEE")
print("EEE")
print("EEEEEEEEEEEEEEEEEEEEEE")
print("EEEEEEEEEEEEEEEEEEEEEE")
print("EEE")
print("EEE")
print("EEE")
print("EEE")
print("EEEEEEEEEEEEEEEEEEEEEE")
print("EEEEEEEEEEEEEEEEEEEEEE")

print("    GGGGGGGGGGGGGGGGGGGGG")
print("   GGGGGGGGGGGGGGGGGGGGGGG")
print("GGG                       GGG")
print("GGG                        GGG")
print("GGG                         GGG")
print("GGG                          GGG")
print("GGG                         GGG")
print("GGG                        GGG")
print("GGG                               ")
print(" GGG                              ")
print("  GGG                             ")
print("   GGG             GGGGGGGGGGGGGGG")
print("    GGG             GGGGGGGGGGGGGGG")
print("     GGG                         GGG")
print("      GGG                       GGG")
print("       GGG                     GGG")
print("        GGG                   GGG")
print("         GGG                 GGG")
print("          GGGGGGGGGGGGGGGGGGGGG")
print("           GGGGGGGGGGGGGGGGGGG")

print("         OOOOOOOOOOOOOOOOOOOOOO")
print("        OOOOOOOOOOOOOOOOOOOOOOOO")
print("      OOOO                    OOOO")
print("     OOOO                      OOOO")
print("    OOOO                        OOOO")
print("   OOOO                          OOOO")
print("  OOOO                            OOOO")
print("  OOOO                            OOOO")
print("   OOOO                          OOOO")
print("    OOOO                        OOOO")
print("     OOOO                      OOOO")
print("      OOOO                    OOOO")
print("        OOOOOOOOOOOOOOOOOOOOOOOO")
print("         OOOOOOOOOOOOOOOOOOOOOO")