print("             IIIII¯\\")
print("            IIIIIII \\")
print("           IIIIIIIII \\")
print("          IIIII IIIII \\")
print("         IIIII / IIIII \\")
print("        IIIII /   IIIII \\")
print("       IIIII /     IIIII \\")
print("      IIIIIIIIIIIIIIIIIII \\")
print("     IIIIIIIIIIIIIIIIIIIII \\")
print("    IIIIII /        IIIIIII \\")
print("   IIIIII /          IIIIIII \\")
print("  IIIIII /            IIIIIII \\")
print(" IIIIII_/              IIIIIII_\\")
print(" ")
print(" ")
print("  IIIIIIIIII¯\       IIIIIIII¯|")
print("  IIIIIIIIIII \      IIIIIIII |")
print("  IIIIIIIIIIII \     IIIIIIII |")
print("  IIIIIIIIIIIII \    IIIIIIII |")
print("  IIIIIIIIIIIIII \   IIIIIIII |")
print("  IIIIIIIIIIIIIII \  IIIIIIII |")
print("  IIIIIIII |IIIIII \ IIIIIIII |")
print("  IIIIIIII | IIIIII \IIIIIIII |")
print("  IIIIIIII |  IIIIIIIIIIIIIII |")
print("  IIIIIIII |   IIIIIIIIIIIIII |")
print("  IIIIIIII |    IIIIIIIIIIIII |")
print("  IIIIIIII |     IIIIIIIIIIII |")
print("  IIIIIIII |      IIIIIIIIIII |")
print("  IIIIIIII |       IIIIIIIIII |")
print("  IIIIIIII_|        IIIIIIIII_|")
print(" ")
print(" ")
print("""
IIIIIIIIIIIIIIIIIIIIII¯¯\\
IIIIIIIIIIIIIIIIIIIIIIII  \\
IIIIIIIIIIIIIIIIIIIIIIIIIII \\
IIIIIIII |         IIIIIIIIII\\
IIIIIIII |           IIIIIIIII |
IIIIIIII |            IIIIIIII |
IIIIIIII |             IIIIIII |
IIIIIIII |             IIIIIII |
IIIIIIII |             IIIIIII |
IIIIIIII |            IIIIIIII |
IIIIIIII |           IIIIIIIII |
IIIIIIII |         IIIIIIIIII /
IIIIIIIIIIIIIIIIIIIIIIIIIIII /
IIIIIIIIIIIIIIIIIIIIIIIII  /
IIIIIIIIIIIIIIIIIIIIIII__/
""")
print("""
IIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIII |          IIIIIIIII
IIIIIII |            IIIIIIIII
IIIIIII |             IIIIIIII
IIIIIII |             IIIIIIII
IIIIIII |            IIIIIIIII
IIIIIII |           IIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIII \\
IIIIIIIIIIIIIIIIIIIIIIIIII \\ 
IIIIIII |         IIIIIIIII \\ 
IIIIIII |          IIIIIIIII \\ 
IIIIIII |           IIIIIIIII \\
IIIIIII |            IIIIIIIII \\ 
IIIIIII |             IIIIIIIII \\
IIIIIII |              IIIIIIIII \\
IIIIIII |               IIIIIIIII \\
""")
print("""
             IIIIII¯/
            IIIIII /
           IIIIII_/

IIIIIIIIIIIIIIIIIIIIIIIIIIIII |
IIIIIIIIIIIIIIIIIIIIIIIIIIIII |
IIIIIIIIIIIIIIIIIIIIIIIIIIIII |
IIIIIIIIIII |
IIIIIIIIIII |
IIIIIIIIIII |
IIIIIIIIIII |_________________
IIIIIIIIIIIIIIIIIIIIIIIIIIIII |
IIIIIIIIIIIIIIIIIIIIIIIIIIIII |
IIIIIIIIIIIIIIIIIIIIIIIIIIIII |
IIIIIIIIIII |
IIIIIIIIIII | 
IIIIIIIIIII |
IIIIIIIIIII |_________________
IIIIIIIIIIIIIIIIIIIIIIIIIIIII |
IIIIIIIIIIIIIIIIIIIIIIIIIIIII |
IIIIIIIIIIIIIIIIIIIIIIIIIIIII |
""")
print("""
         IIIIIIIIIIIIIIIIIIIII¯/
    IIIIIIIIIIIIIIIIIIIIIIIII /
  IIIIIIIIIIIIIIIIIIIIIIIIII_/
IIIIIIIIIIIIIII /
IIIIIIIIIIIIII /
IIIIIIIIIIIIII |
  IIIIIIIIIIIIIIII
    IIIIIIIIIIIIIIII
      IIIIIIIIIIIIIIIII
          IIIIIIIIIIIIIIIII
             IIIIIIIIIIIIIIII
               IIIIIIIIIIIIIII
     ________IIIIIIIIIIIIIIIII
    IIIIIIIIIIIIIIIIIIIIIIIIII
  IIIIIIIIIIIIIIIIIIIIIIIIII
  IIIIIIIIIIIIIIIIIIIIIIII
    
""")