print("—————")
print("|                 ")
print("|                 ")
print("|————  ")
print("|                 ")
print("|                ")
print("|                ")
print("")
print("")
print("")
print("—————----— ")
print("    |               ")  
print("    |               ") 
print("    |               ") 
print("    |               ") 
print("    |               ") 
print(" ———               ") 
print("")
print("")
print("")
print("    /\      ")
print("   /  \     ")
print("  /    \     ")
print(" /——--- \   ")
print("/        \  ")
print("")
print("")
print("")
print("________")
print("|       |")
print("|       |")
print("|————-- |")
print("|        \\")
print("|         \\")
print("|          \\")
print("|           \\")
