print("MMM      MMM   MMM      MMM   AAAAAAAAAAAA   AAAAAAAAAAAA")
print("MMMM    MMMM   MMMM    MMMM   AAAAAAAAAAAA   AAAAAAAAAAAA")
print("MMMM    MMMM   MMMM    MMMM   AA        AA   AA        AA")
print("MM MM  MM MM   MM MM  MM MM   AA        AA   AA        AA")
print("MM MM  MM MM   MM MM  MM MM   AA        AA   AA        AA")
print("MM  MMMM  MM   MM  MMMM  MM   AAAAAAAAAAAA   AAAAAAAAAAAA")
print("MM   MM   MM   MM   MM   MM   AA        AA   AA        AA")
print("MM        MM   MM        MM   AA        AA   AA        AA")
print("MM        MM   MM        MM   AA        AA   AA        AA")
print("MM        MM   MM        MM   AA        AA   AA        AA")
print("MM        MM   MM        MM   AA        AA   AA        AA")