ascii
print ("Ni       Ni")
print ("Ni Ni    Ni")
print ("Ni   Ni  Ni")
print ("Ni    Ni Ni")
print ("Ni       Ni")
print ("           ")
print  ("CoCoCoCoCoCo")
print ("     Co    ")
print ("     Co    ")
print ("     Co    ")
print ("     Co    ")
print ("     Co    ")
print  ("CoCoCoCoCoCo")
print ("LasLasLasLasLas")
print ("Las")
print ("Las")
print ("Las")
print ("Las")
print ("LasLasLasLasLas")
print ("               ")
print(" !!!!!!!!!!!!!!")
print("!!!          !!!")
print("!!!          !!!")
print("!!!          !!!")
print("!!!          !!!")
print(" !!!!!!!!!!!!!!")
