print("FFFFFFFFFFFFFFFFFF")
print("FFFFFFFFFFFFFFFFFF")
print("FFF")
print("FFF")
print("FFFFFFFFFFFFFFF")
print("FFFFFFFFFFFFFFF")
print("FFF")
print("FFF")
print("FFF")
print("FFF") 
print("FFF")
print("")
print("RRRRRRRRRRRRRRRR")                                   
print("RRRRRRRRRRRRRRRRR")
print("RRR            RRR")
print("RRR             RRR")
print("RRR             RRR")
print("RRR            RRR")
print("RRRRRRRRRRRRRRRRRR")
print("RRRRRRRRRRRRRRRRR")
print("RRR            RRR")
print("RRR             RRR")
print("RRR              RRR")
print("RRR               RRR")
print("RRR                RRR")
print("")
print("AAAAAAAAAAAAAAAAA")
print("AAAAAAAAAAAAAAAAA")
print("AAA           AAA")
print("AAA           AAA")
print("AAA           AAA")
print("AAA           AAA")
print("AAAAAAAAAAAAAAAAA")
print("AAAAAAAAAAAAAAAAA")
print("AAA           AAA")
print("AAA           AAA")
print("AAA           AAA")
print("AAA           AAA")
print("AAA           AAA")
print("")
print("NNNNNN        NNN")
print("NNN NNN       NNN")
print("NNN  NNN      NNN")
print("NNN   NNN     NNN")
print("NNN    NNN    NNN")
print("NNN     NNN   NNN")
print("NNN      NNN  NNN")
print("NNN       NNN NNN")
print("NNN        NNNNNN")
print("NNN         NNNNN")
print("NNN          NNNN")
print("NNN           NNN")
print("")
print("")
print("")
print("")
print("")
print("RRRRRRRRRRRRRRRR")                                   
print("RRRRRRRRRRRRRRRRR")
print("RRR            RRR")
print("RRR             RRR")
print("RRR             RRR")
print("RRR            RRR")
print("RRRRRRRRRRRRRRRRRR")
print("RRRRRRRRRRRRRRRRR")
print("RRR            RRR")
print("RRR             RRR")
print("RRR              RRR")
print("RRR               RRR")
print("RRR                RRR")
print("")
print("AAA            AAA")
print("AAA            AAA")
print("AAA            AAA")
print("AAA            AAA")
print("AAA            AAA")
print("AAA            AAA")
print("AAA            AAA")
print("AAA            AAA")
print("AAA            AAA")
print("AAA            AAA")
print("AAA            AAA")
print("AAAAAAAAAAAAAAAAAA")
print("AAAAAAAAAAAAAAAAAA")
print("")
print("IIIIIIIIIIIIIIIIIII")
print("IIIIIIIIIIIIIIIIIII")
print("        III")
print("        III")
print("        III")
print("        III")
print("        III")
print("        III")
print("        III")
print("        III")
print("IIIIIIIIIIIIIIIIIII")
print("IIIIIIIIIIIIIIIIIII")
print("")
print("ZZZZZZZZZZZZZZZZZ")
print("ZZZZZZZZZZZZZZZZZ")
print("             ZZZ")
print("            ZZZ")
print("           ZZZ")
print("          ZZZ")
print("         ZZZ")
print("        ZZZ")
print("       ZZZ")
print("      ZZZ")
print("     ZZZ")
print("    ZZZ")
print("   ZZZ")
print("  ZZZ")
print(" ZZZ")
print("ZZZZZZZZZZZZZZZZZ")
print("ZZZZZZZZZZZZZZZZZ")
print("")
